# Generated by Django 5.1.7 on 2025-03-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=700)),
                ('contact', models.CharField(max_length=12)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
