# Generated by Django 5.1.7 on 2025-03-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_notes',
            name='contact',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
