# Generated by Django 5.1.7 on 2025-03-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_create_notes_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_notes',
            name='note',
            field=models.TextField(max_length=700, null=True),
        ),
    ]
